/**
 * Firebase Auth: the identity backend, and the web app config the browser needs.
 *
 * Neither existed until now, and their absence was invisible in a way worth
 * recording. The web app picks its auth adapter from whether Firebase config is
 * present:
 *
 *     firebaseConfigured ? createFirebaseAuth() : createDevAuth()
 *
 * With no config in the production build, that silently chose the *development*
 * adapter — which prints verification codes to the browser console, signs a
 * user in locally, and issues no real ID token. The deployed site therefore
 * looked like it had auth, let anyone reach /app, and 401'd on every API call.
 *
 * Nothing failed loudly. That fallback is now fail-closed in the app (see
 * AuthProvider), and this file makes sure there is real config to find.
 */

# Identity Platform is what Firebase Auth runs on. Creating this config is the
# equivalent of clicking "Get started" on the Auth console page — until it
# exists, the admin API returns 404 for the project.
resource "google_identity_platform_config" "auth" {
  provider = google-beta
  project  = var.project_id

  # Firebase Auth refuses sign-in from any origin not listed here, and the
  # defaults cover only <project>.firebaseapp.com and <project>.web.app — not
  # the site we actually serve. Without these, sign-in fails on the real domain
  # with an unauthorized-domain error while working fine on the default one,
  # which is a confusing way to discover it.
  authorized_domains = compact([
    "localhost",
    "${var.project_id}.firebaseapp.com",
    "${var.project_id}.web.app",
    "${var.hosting_site_id}.web.app",
    var.custom_domain,
  ])

  sign_in {
    # Email + password + verification codes, which is what the product's own
    # sign-up flow implements. Anonymous is deliberately off: an anonymous user
    # would satisfy `requireUser` in the gateway without anyone having proved
    # anything.
    allow_duplicate_emails = false

    email {
      enabled           = true
      password_required = true
    }

    anonymous {
      enabled = false
    }
  }

  lifecycle {
    # Blocks the API populates with its own defaults whether or not they are
    # declared here. Left alone they produce an identical "remove these"
    # diff on every single plan — the same noise as the service-level
    # `scaling` block in backend-service.
    #
    # Safe to ignore because neither is a control being relied on: phone
    # sign-in has no client code and no route, and tenants are off. Turning
    # either ON would be a deliberate change made here, and would then no
    # longer be ignored drift — it would be a new declared value.
    ignore_changes = [
      multi_tenant,
      sign_in[0].phone_number,
    ]
  }

  # Google sign-in needs an OAuth client id and secret, which cannot be created
  # by Terraform — the consent screen is a console flow. It is wired separately;
  # see google_identity_platform_default_supported_idp_config below.
}

resource "google_firebase_web_app" "this" {
  provider = google-beta
  project  = var.project_id

  display_name = "AllTheWay (${var.env})"

  # The app is what the browser SDK identifies itself as. Deleting and
  # recreating it changes the appId, which invalidates any client still holding
  # the old one, so it outlives a normal destroy.
  deletion_policy = "ABANDON"

  depends_on = [google_identity_platform_config.auth]
}

# The apiKey and authDomain the browser needs. Read rather than constructed:
# the API key is generated by Firebase and is not derivable from the project id.
data "google_firebase_web_app_config" "this" {
  provider   = google-beta
  project    = var.project_id
  web_app_id = google_firebase_web_app.this.app_id
}

# Google sign-in, only when an OAuth client has been created by hand.
#
# The consent screen and OAuth client are console-only flows, so this stays
# optional rather than blocking every apply on a manual step. Without it, email
# and password still work and the Google button fails with a clear provider
# error instead of a blank page.
resource "google_identity_platform_default_supported_idp_config" "google" {
  count = var.google_oauth_secrets == null ? 0 : 1

  provider = google-beta
  project  = var.project_id

  idp_id        = "google.com"
  client_id     = data.google_secret_manager_secret_version.google_oauth_client_id[0].secret_data
  client_secret = data.google_secret_manager_secret_version.google_oauth_client_secret[0].secret_data
  enabled       = true

  depends_on = [google_identity_platform_config.auth]
}
