import type { ArtifactDetail, ArtifactKind } from "@alltheway/contracts";

import { addVersion, createArtifact, getArtifact } from "./repos/artifacts.js";

/**
 * Bytes from a confirmed media call, written as an artifact version.
 *
 * `generate_image` (and the video tools) return JSON with a base64 `content`
 * field. The gateway used to keep only a 2,000-character text slice, so the
 * still existed for one response and then vanished. Studio and Canvas both
 * need the object that was made.
 */

export const MEDIA_TOOLS = new Set([
  "generate_image",
  "draft_video",
  "poll_draft_video",
  "render_video",
]);

export const STUDIO_SESSION_ID = "studio";

export type MediaPayload = {
  error?: string;
  body?: Buffer;
  mimeType?: string;
  model?: string;
};

export type VideoStart = {
  error?: string;
  operation?: string;
  model?: string;
  seconds?: number;
};

export type VideoPoll = {
  error?: string;
  done: boolean;
  body?: Buffer;
  mimeType?: string;
  model?: string;
};

const IMAGE_PREFIX = "image/";
const VIDEO_PREFIX = "video/";

/** Protobuf JSON often wraps scalars as `{ stringValue: "..." }`. */
function asString(node: unknown): string {
  if (typeof node === "string") return node;
  if (node && typeof node === "object") {
    const rec = node as Record<string, unknown>;
    if (typeof rec.stringValue === "string") return rec.stringValue;
  }
  return "";
}

function asNumber(node: unknown): number | undefined {
  if (typeof node === "number" && Number.isFinite(node)) return node;
  if (node && typeof node === "object") {
    const rec = node as Record<string, unknown>;
    if (typeof rec.numberValue === "number") return rec.numberValue;
  }
  return undefined;
}

function asBool(node: unknown): boolean | undefined {
  if (typeof node === "boolean") return node;
  if (node && typeof node === "object") {
    const rec = node as Record<string, unknown>;
    if (typeof rec.boolValue === "boolean") return rec.boolValue;
  }
  return undefined;
}

/**
 * Find generated bytes (or a model error) in an A2A task.
 *
 * The connector puts `{ data: { content, mimeType } }` on the result
 * artifact. Walking is necessary because the SDK wraps that in a Task.
 * Base64 is not treated as readable detail — it would drown the note.
 */
export function mediaFromConnectorTask(task: unknown): MediaPayload {
  let error = "";
  let content = "";
  let mimeType = "";
  let model = "";

  const walk = (node: unknown, depth: number): void => {
    if (!node || typeof node !== "object" || depth > 12) return;
    if (content && mimeType) return;
    const rec = node as Record<string, unknown>;
    const err = (asString(rec.error) || asString(rec.reason)).trim();
    if (err && !error) error = err;
    const maybeContent = asString(rec.content);
    const mime = asString(rec.mimeType);
    if (maybeContent.length > 80 && (mime.startsWith(IMAGE_PREFIX) || mime.startsWith(VIDEO_PREFIX))) {
      content = maybeContent;
      mimeType = mime;
    }
    const maybeModel = asString(rec.model).trim();
    if (maybeModel && !model) model = maybeModel;
    const dataStr = asString(rec.data);
    if (dataStr.startsWith("{")) {
      try {
        walk(JSON.parse(dataStr), depth + 1);
      } catch {
        /* not JSON */
      }
    }
    for (const value of Object.values(rec)) {
      if (Array.isArray(value)) value.forEach((item) => walk(item, depth + 1));
      else if (value && typeof value === "object") walk(value, depth + 1);
    }
  };
  walk(task, 0);

  if (content && mimeType) {
    const body = Buffer.from(content, "base64");
    if (body.byteLength === 0) return { error: error || "The still came back empty." };
    return { body, mimeType, model };
  }
  if (error) return { error };
  return {};
}

/**
 * A draft_video start: an operation name, not bytes. Vertex has begun billing
 * once this is present.
 */
export function videoStartFromConnectorTask(task: unknown): VideoStart {
  let error = "";
  let operation = "";
  let model = "";
  let seconds: number | undefined;

  const walk = (node: unknown, depth: number): void => {
    if (!node || typeof node !== "object" || depth > 12) return;
    const rec = node as Record<string, unknown>;
    const err = (asString(rec.error) || asString(rec.reason)).trim();
    if (err && !error) error = err;
    const op = asString(rec.operation).trim();
    if (op && !operation) operation = op;
    const maybeModel = asString(rec.model).trim();
    if (maybeModel && !model) model = maybeModel;
    const sec = asNumber(rec.seconds);
    if (sec !== undefined && seconds === undefined) seconds = sec;
    const dataStr = asString(rec.data);
    if (dataStr.startsWith("{")) {
      try {
        walk(JSON.parse(dataStr), depth + 1);
      } catch {
        /* not JSON */
      }
    }
    for (const value of Object.values(rec)) {
      if (Array.isArray(value)) value.forEach((item) => walk(item, depth + 1));
      else if (value && typeof value === "object") walk(value, depth + 1);
    }
  };
  walk(task, 0);

  if (operation) return { operation, model, seconds };
  if (error) return { error };
  return {};
}

export function videoPollFromConnectorTask(task: unknown): VideoPoll {
  const media = mediaFromConnectorTask(task);
  if (media.body && media.mimeType) {
    return { done: true, body: media.body, mimeType: media.mimeType, model: media.model };
  }
  if (media.error) return { done: true, error: media.error };

  let done: boolean | undefined;
  const walk = (node: unknown, depth: number): void => {
    if (!node || typeof node !== "object" || depth > 12) return;
    if (done !== undefined) return;
    const rec = node as Record<string, unknown>;
    const flag = asBool(rec.done);
    if (flag !== undefined) done = flag;
    const dataStr = asString(rec.data);
    if (dataStr.startsWith("{")) {
      try {
        walk(JSON.parse(dataStr), depth + 1);
      } catch {
        /* not JSON */
      }
    }
    for (const value of Object.values(rec)) {
      if (Array.isArray(value)) value.forEach((item) => walk(item, depth + 1));
      else if (value && typeof value === "object") walk(value, depth + 1);
    }
  };
  walk(task, 0);

  return { done: done === true };
}

function kindOf(mimeType: string, tool: string): ArtifactKind {
  if (mimeType.startsWith(VIDEO_PREFIX) || tool.includes("video")) return "video";
  return "image";
}

function titleFrom(prompt: string): string {
  const trimmed = prompt.trim().replace(/\s+/g, " ");
  if (!trimmed) return "Untitled still";
  return trimmed.length > 80 ? `${trimmed.slice(0, 77)}…` : trimmed;
}

/**
 * Write the bytes as v1 of a new artifact, or as the next version of one
 * the user is iterating on.
 */
export async function persistGeneratedMedia(opts: {
  uid: string;
  sessionId: string;
  tool: string;
  prompt: string;
  task: unknown;
  artifactId?: string;
}): Promise<{ artifact: ArtifactDetail; kind: ArtifactKind } | { error: string } | null> {
  const payload = mediaFromConnectorTask(opts.task);
  if (payload.error && !payload.body) return { error: payload.error };
  if (!payload.body || !payload.mimeType) return null;

  const kind = kindOf(payload.mimeType, opts.tool);
  const prompt = opts.prompt.trim();

  try {
    if (opts.artifactId) {
      await addVersion(opts.uid, opts.artifactId, {
        body: payload.body,
        mimeType: payload.mimeType,
        producedBy: "agent",
        prompt,
        correction: "",
      });
      const artifact = await getArtifact(opts.uid, opts.artifactId);
      if (!artifact) {
        return {
          error:
            kind === "video"
              ? "The clip was made but could not be opened."
              : "The still was made but could not be opened.",
        };
      }
      return { artifact, kind };
    }

    const artifact = await createArtifact(opts.uid, {
      kind,
      title: titleFrom(prompt),
      sessionId: opts.sessionId || STUDIO_SESSION_ID,
      body: payload.body,
      mimeType: payload.mimeType,
      prompt,
      provenance: {
        agentId: "media",
        cardVersion: "1.0.0",
        model: payload.model ?? "",
        sources: [],
      },
    });
    return { artifact, kind };
  } catch (err) {
    console.warn(`[media] persist failed: ${(err as Error).message}`);
    return {
      error:
        kind === "video"
          ? "The clip finished but could not be saved."
          : "The still was made but could not be saved.",
    };
  }
}
